# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef1b651991e15b3abaa0b75d5df7ba6a3ac8ec7d8a1793725f89786a66a3aa727c03ca8c65e065e6fb73e49ba6b674853695936da8ea8773e1374745b55e7a82

test:
  secret_key_base: 418acfffd0a4e09d2bbe218fe22b69c345abed7b3517c59fb4c575bdcb9e48ee6e234d83867537312ab37cd05a258b7182c46d7f7d130b97f8a8fe1027e22527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
